### ISSUE TITLE
Missing Functions like `GreaterThan` for SymPy version 0.5.0

### ISSUE THREAD

**Issue by Marlin-Na** [JuliaPy/SymPy.jl#141]
In SymPy 0.4 I thought I was able to do:

```julia
@syms x y
GreaterThan(x, y)
# y <= x  (In my memory, it returned this for SymPy 0.4)
```

However, it seems the functions like `GreaterThan` are not there but I found `SymPy.GreaterThan` which does work as expected.

```julia
using SymPy
@syms x y
SymPy.GreaterThan(x, y)
# ERROR: MethodError: no method matching GreaterThan(::SymPy.Sym, ::SymPy.Sym)
SymPy.GreaterThan(x + 1, x)
# ERROR: MethodError: no method matching GreaterThan(::SymPy.Sym, ::SymPy.Sym)
```

Curiously, `SymPy.GreaterThan` works for non-symbol:
```julia
SymPy.GreaterThan(2, 1)
# True
```

Are these functions removed on prupose? Thanks!

**Comment by jverzani** [comment]
There are the aliases, `Gt`, `Ge`, ... For these longer forms, I have left a [note](https://github.com/JuliaPy/SymPy.jl/blob/master/src/logical.jl#L6) that these longer forms were restricted to `T <: Real` (and hence not Sym) so that piecewise functions could be lambdified. That seems like a technical hurdle that should be overcome, rather than a good reason.
