### ISSUE TITLE
inv([0 b; c d])

### ISSUE THREAD

**Issue by Gmunozq** [JuliaPy/SymPy.jl#207]
I can't invert a matrix `A` when `A[1,1]=0`

The next code generates an error:
`b,c,d=symbols("b c d")
inv([0 b; c d])`

**Comment by mzaffalon** [comment]
It looks like an unfortunate way `sympy.py` writes the expression. `sympy.py` 1.1.1 shipped with Anaconda computes the inverse correctly when the entry `A[1,1]=0`, see below. 
```
julia> inv([a b; c d])
2×2 Array{SymPy.Sym,2}:
 (1 + b*c/(a*(d - b*c/a)))/a  -b/(a*(d - b*c/a))
          -c/(a*(d - b*c/a))       1/(d - b*c/a)
```
```
In [3]: M = Matrix([[0, b], [c, d]])

In [4]: M**(-1)
Out[4]: 
Matrix([
[-d/(b*c), 1/c],
[     1/b,   0]])

```

**Comment by jverzani** [comment]
This is an unfortunate result of using Julia's generic `inv` function to compute the inverse of a matrix. (We try and use generic Julia implementations for matrices rather than SymPy ones, as we convert symbolic arrays to  Array{Sym,.} instead of working with symbolic arrays.) 

For this particular problem, you can try sympy's `inverse_LU`, `inverse_GE`, or `inverse_ADJ` directly in place of julia's `inv`. 

Alternatively, this works: `sympy[:Matrix](A)[:inv]()`, where `A` is your matrix `[0 b; c d]`.

It is interesting that this works in 1.1.1, my 1.1 installation produces a similar error.

**Comment by jverzani** [comment]
As of #229 `inv` for a matrix uses `inverse_LU` and not a generic method. This should work now without complaint.
