### ISSUE TITLE
Getting intermittent "Expression does not lambdify" errors

### ISSUE THREAD

**Issue by djsegal** [JuliaPy/SymPy.jl#235]
ArgumentError("Expression does not lambdify") 

------

Three example expressions are:

+ `(0.638890180868381*sqrt((1 - rho^2)^0.23338692645203*(1 - 0.132792457927795*rho)^2) + sqrt(1.0 + 0.20731365147451*(1 - rho^2)^0.23338692645203*(1 - 0.132792457927795*rho)^2))^2`

+ `(0.538051345483413*sqrt((1 - rho^2)^0.212801961678713*(1 - 0.0590459519484148*rho)^2) + sqrt(1.0 + 0.0654387512861676*(1 - rho^2)^0.212801961678713*(1 - 0.0590459519484148*rho)^2))^2`

+ `(1.02848319244369*sqrt((1 - rho^2)^0.318614751664346*(1 - 0.087294736303311*rho)^2) + sqrt(1.0 + 0.901195971198156*(1 - rho^2)^0.318614751664346*(1 - 0.087294736303311*rho)^2))^2`

-----

Can't seem to reproduce with the formulas given. May be some other try-catch error?

**Comment by jverzani** [comment]
Are you on master? I recently made a change to avoid doing this SymPy side (https://github.com/JuliaPy/SymPy.jl/blob/master/src/lambdify.jl#L148). There were some cases where dot syntax was not evaluating as desired. Otherwise, maybe you could try pinpointing the issue by calling the underlying `walk_expression` function. I can't replicate with these three.

**Comment by djsegal** [comment]
Don't know if I can replicate this anymore. Closing this
