### ISSUE TITLE
`conj` is not type stable

### ISSUE THREAD

**Issue by tkoolen** [JuliaPy/SymPy.jl#244]
```julia
julia> using SymPy

julia> @syms x
(x,)

julia> @code_warntype conj(x)
Body::Any
169 1 ─ %1 = SymPy.sympy_meth::typeof(sympy_meth)                                                                                                          │╻╷  conjugate
    │   %2 = invoke SymPy.:(#sympy_meth#539)($(QuoteNode(Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}()))::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, %1::Function, "conjugate"::String, _2::Sym)::Any
    └──      return %2 
```

I believe this used to be type stable in an earlier version, and I don't see any reason for it not to be. This is the cause of https://github.com/JuliaRobotics/RigidBodyDynamics.jl/issues/501.

**Comment by jverzani** [comment]
If I have this right, the issue comes from the automatic conversion (using PyAny) in a call that essentially looks like:

```
_sympy_meth(meth, args...; kwargs...) =  PyCall.pycall(sympy[string(meth)], PyCall.PyAny, args...; kwargs...)
```

Were it defined like:
```
__sympy_meth(meth, args...; kwargs...) =  Sym(PyCall.pycall(sympy[string(meth)], PyCall.PyObject, args...; kwargs...))
```

I get:
```
julia> @btime __sympy_meth(:conjugate, x)
  1.806 μs (9 allocations: 288 bytes)

julia> @btime _sympy_meth(:conjugate, x)
  7.003 μs (11 allocations: 320 bytes)
```

The issue is that definition won't work for all cases where `sympy_meth` is used. I might need to refactor some things abit. If this is just for one function, it could be easily special cased. If it is more general, I'll have to find some time to identify where the faster method will fail, and work around those.

**Comment by tkoolen** [comment]
Thanks for investigating!

**Comment by jverzani** [comment]
I just put in a PR that I hope addresses this issue.  Could you check against your package and report back?

**Comment by tkoolen** [comment]
Thanks for the quick response. I can confirm that everything is working as it should on SymPy master.
