### ISSUE TITLE
sympy.Sum doesn't work!

### ISSUE THREAD

**Issue by Islam0mar** [JuliaPy/SymPy.jl#273]
The following code give error `ERROR: MethodError: no method matching getindex(::Sym, ::Sym)`
```
using SymPy
i,j = sympy.symbols("i j", integer=True)
x = sympy.IndexedBase("x")
a = sympy.Sum(x[i], (i, 1, j))
```
I tried to quote :(x[i]) without success.

How to use Sum and Product in Julia?

**Comment by jverzani** [comment]
Yes, `[` means something in `SymPy.jl` different from Python, where *I think* `__getitem__` works. Is this what you expect?

```
julia> a = sympy.Sum(x.__getitem__(i), (i, 1, j))
  j       
 ___      
 ╲        
  ╲   x[i]
  ╱       
 ╱        
 ‾‾‾      
i = 1     
```

You get an error message that indicates this could be addressed by:

```
Base.getindex(x::Sym, xs::Sym...) = x.__getitem__(xs...)
```

Then you have:

```
julia> a = sympy.Sum(x[i], (i, 1, j))
  j       
 ___      
 ╲        
  ╲   x[i]
  ╱       
 ╱        
 ‾‾‾      
i = 1     
```

If this is what you want, try opening that as an issue, so that we can gather some feedback. As you see, the "fix" isn't hard if it doesn't trample on anything else.

**Comment by Islam0mar** [comment]
Thanks. 
It works well for me now.
