### ISSUE TITLE
Can't integrate constant functions

### ISSUE THREAD

**Issue by lucasvreis** [JuliaPy/SymPy.jl#320]
If I do:
```julia
using SymPy
integrate(x -> 1, 0, 1)
```
It just assumes the first argument is an Int, and throws an error as there are no methods implementing it. Same for other numerical types, even though `typeof(x -> 1) <: Function`.

Edit: now I see this is because some `integrate` methods call the python method assuming `f(x)` always has type `Sym`, which is not the case for constant functions.

**Comment by lucasvreis** [comment]
There is of course an easy fix: implement a new method for the type Number. 

https://github.com/JuliaPy/SymPy.jl/blob/b6cfd511bbbb4879d9e5e0a43dda957040f540f9/src/mathfuns.jl#L62-L77

After those lines, one can just add:
```julia
function integrate(c::Number, a::Number, b::Number)
    c * (b - a)
end
function integrate(c::Number)
    x = symbols("x")
    c * x
end
```

**Comment by lucasvreis** [comment]
And now I have a question regarding this and the previous issue: I see the package uses `symbols("x")` when in need of creating a dummy variable; can't this introduce issues if I have previously set restrictions for `x`, like declaring it to be positive? That is why I used the `dummy` method in my former issue.

**Comment by jverzani** [comment]
Thanks! I  solved  this a bit differently, by calling `sympy.integrate` rather than convert  to  Sym. Thanks for pointing out the use of `Dummy` too! I  added that for  that for the helper function `limit`, `diff`,  and `integrate` for functions.

As  for  extending to  constants, I  think   that   should  be held off.  If I  didn't use the function  interface in  the classroom,  I'd  drop  it rather  than extend it.
